// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list_proyectos.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function jsonContent(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}
function errorContent(msg) {
  return {
    content: [{ type: "text", text: msg }],
    isError: true
  };
}

// src/lib/mcp/tools/list_proyectos.ts
var list_proyectos_default = defineTool({
  name: "list_proyectos",
  title: "Listar proyectos",
  description: "Lista proyectos visibles para el usuario autenticado. Permite filtrar por texto (nombre/direcci\xF3n/comuna) y estado de obra.",
  inputSchema: {
    search: z.string().optional().describe("Texto a buscar en nombre, direcci\xF3n o comuna."),
    estado_obra: z.string().optional().describe("Filtrar por estado de obra exacto."),
    limit: z.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, estado_obra, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorContent("No autenticado");
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("proyectos").select("id, nombre, direccion, comuna, estado_obra, estado_amc, monto_estimado, adjudicado, fecha_ingreso").order("fecha_ingreso", { ascending: false }).limit(limit);
    if (estado_obra) q = q.eq("estado_obra", estado_obra);
    if (search) q = q.or(`nombre.ilike.%${search}%,direccion.ilike.%${search}%,comuna.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return errorContent(error.message);
    return jsonContent({ count: data?.length ?? 0, proyectos: data ?? [] });
  }
});

// src/lib/mcp/tools/get_proyecto.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
var get_proyecto_default = defineTool2({
  name: "get_proyecto",
  title: "Obtener proyecto",
  description: "Devuelve toda la informaci\xF3n de un proyecto por ID.",
  inputSchema: {
    id: z2.string().uuid().describe("ID del proyecto.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return errorContent("No autenticado");
    const { data, error } = await supabaseForUser(ctx).from("proyectos").select("*").eq("id", id).maybeSingle();
    if (error) return errorContent(error.message);
    if (!data) return errorContent("Proyecto no encontrado");
    return jsonContent(data);
  }
});

// src/lib/mcp/tools/list_alertas.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.23.8";
var list_alertas_default = defineTool3({
  name: "list_alertas",
  title: "Listar alertas",
  description: "Lista alertas de seguimiento visibles para el usuario autenticado. Por defecto solo pendientes (no completadas ni eliminadas).",
  inputSchema: {
    only_mine: z3.boolean().default(true).describe("Solo alertas donde soy responsable."),
    include_completed: z3.boolean().default(false),
    proyecto_id: z3.string().uuid().optional(),
    limit: z3.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_mine, include_completed, proyecto_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorContent("No autenticado");
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("alertas").select("id, titulo, texto, fecha_seguimiento, completada, proyecto_id, empresa_id, usuario_responsable_id, created_at").eq("deleted", false).order("fecha_seguimiento", { ascending: true }).limit(limit);
    if (!include_completed) q = q.eq("completada", false);
    if (proyecto_id) q = q.eq("proyecto_id", proyecto_id);
    if (only_mine) q = q.eq("usuario_responsable_id", ctx.getUserId());
    const { data, error } = await q;
    if (error) return errorContent(error.message);
    return jsonContent({ count: data?.length ?? 0, alertas: data ?? [] });
  }
});

// src/lib/mcp/tools/list_empresas.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.23.8";
var list_empresas_default = defineTool4({
  name: "list_empresas",
  title: "Listar empresas",
  description: "Lista empresas visibles para el usuario autenticado.",
  inputSchema: {
    search: z4.string().optional().describe("Filtro por nombre."),
    limit: z4.number().int().min(1).max(200).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorContent("No autenticado");
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("empresas").select("id, nombre, estado, fecha_inicio_relacion").order("nombre", { ascending: true }).limit(limit);
    if (search) q = q.ilike("nombre", `%${search}%`);
    const { data, error } = await q;
    if (error) return errorContent(error.message);
    return jsonContent({ count: data?.length ?? 0, empresas: data ?? [] });
  }
});

// src/lib/mcp/tools/list_clientes.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.23.8";
var list_clientes_default = defineTool5({
  name: "list_clientes",
  title: "Listar clientes",
  description: "Lista clientes visibles para el usuario autenticado.",
  inputSchema: {
    search: z5.string().optional().describe("Filtro por nombre o contacto."),
    limit: z5.number().int().min(1).max(200).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorContent("No autenticado");
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("clientes").select("id, nombre, contacto, email, telefono, categoria_id").order("nombre", { ascending: true }).limit(limit);
    if (search) q = q.or(`nombre.ilike.%${search}%,contacto.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return errorContent(error.message);
    return jsonContent({ count: data?.length ?? 0, clientes: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "bprwbhvhuetjnmsjqfcm";
var mcp_default = defineMcp({
  name: "amc-comercial-mcp",
  title: "AMC Comercial",
  version: "0.1.0",
  instructions: "Herramientas para AMC Gesti\xF3n Comercial. Permite listar y consultar proyectos, alertas de seguimiento, empresas y clientes del usuario autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_proyectos_default,
    get_proyecto_default,
    list_alertas_default,
    list_empresas_default,
    list_clientes_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
